# LOCAL ENV TESTS
###
GET http://localhost:3000/transactions

###
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "amount": 25,
  "type": "food",
  "transactionDate": "1980-09-12",
  "description": "This was a transaction to buy chips"
}

# PROD ENV TESTS
###
GET https://budget-tracker-api-3hgw.onrender.com/transactions

###
POST https://budget-tracker-api-3hgw.onrender.com/transactions
Content-Type: application/json

{
  "amount": 28,
  "type": "food",
  "transactionDate": "1980-09-12",
  "description": "This was a transaction to buy chips"
}